apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-exec-env
  namespace: ansible-ee
  labels:
    app: ansible-exec-env
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ansible-exec-env
  template:
    metadata:
      labels:
        app: ansible-exec-env
    spec:
      containers:
      - name: ansible-exec-env
        image: quay.io/joeweibel77/ubi9-2.18.2-ee-python312:latest
        imagePullPolicy: IfNotPresent
        command: ["tail", "-f", "/dev/null"]
