---
collections:
  - name: ansible.netcommon
    version: 7.1.0
  - name: ansible.posix
    version: 2.0.0
  - name: ansible.scm
    version: 3.0.0
  - name: ansible.snmp
    version: 3.0.0
  - name: ansible.utils
    version: 5.1.2
  - name: ansible.windows
    version: 2.7.0
  - name: community.docker
    version: 4.4.0
  - name: community.network
    version: 5.1.0
  - name: community.general
    version: 10.3.1
  - name: community.dns
    version: 3.2.0
  - name: community.ciscosmb
    version: 1.0.10
  - name: community.crypto
    version: 2.25.0
  - name: community.fortios
    version: 1.0.0
  - name: community.hashi_vault
    version: 6.2.0
  - name: community.healthchecksio
    version: 1.3.1
  - name: community.mongodb
    version: 1.7.9
  - name: community.mysql
    version: 3.12.0
  - name: community.postgresql
    version: 3.10.2
  - name: community.proxysql
    version: 1.6.0
  - name: community.vmware
    version: 5.3.0
  - name: containers.podman
    version: 1.16.3
  - name: netbox.netbox
    version: 3.20.0
#  - name: kubernetes.core This breaks the creation of the image because it looks for openshift-clients
#    version: 5.1.0
