---
collections:
  - name: community.docker
    version: 4.4.0
  - name: community.network
    version: 5.1.0
  - name: containers.podman
    version: 1.16.3
  - name: ansible.netcommon
    version: 7.1.0
  - name: community.general
    version: 10.3.1
  - name: ansible.windows
    version: 2.7.0
